USE DotNetAPI;
GO

-- Seed data for JobInfo table
INSERT INTO APISchema.JobInfo (JobTitle, Department, Salary) VALUES
('Software Developer', 'IT', 70000.00),
('Project Manager', 'IT', 90000.00),
('HR Specialist', 'HR', 60000.00),
('Data Analyst', 'Finance', 75000.00),
('Marketing Manager', 'Marketing', 85000.00),
('Sales Representative', 'Sales', 55000.00),
('Customer Support', 'Support', 50000.00);
GO

-- Seed data for Users table
INSERT INTO APISchema.Users (FirstName, LastName, Email, Active, JobId) VALUES
('John', 'Doe', 'john.doe@example.com', 1, 1),
('Jane', 'Smith', 'jane.smith@example.com', 1, 2),
('Alice', 'Johnson', 'alice.johnson@example.com', 1, 3),
('Robert', 'Brown', 'robert.brown@example.com', 1, 4),
('Michael', 'Davis', 'michael.davis@example.com', 1, 5),
('Jennifer', 'Wilson', 'jennifer.wilson@example.com', 1, 6),
('William', 'Moore', 'william.moore@example.com', 1, 7),
('David', 'Taylor', 'david.taylor@example.com', 1, 1),
('Richard', 'Anderson', 'richard.anderson@example.com', 1, 2),
('Joseph', 'Thomas', 'joseph.thomas@example.com', 1, 3),
('Charles', 'Jackson', 'charles.jackson@example.com', 1, 4),
('Thomas', 'White', 'thomas.white@example.com', 1, 5),
('Patricia', 'Harris', 'patricia.harris@example.com', 1, 6),
('Linda', 'Martin', 'linda.martin@example.com', 1, 7),
('Barbara', 'Thompson', 'barbara.thompson@example.com', 1, 1),
('Elizabeth', 'Garcia', 'elizabeth.garcia@example.com', 1, 2),
('James', 'Martinez', 'james.martinez@example.com', 1, 3),
('Mary', 'Robinson', 'mary.robinson@example.com', 1, 4),
('Susan', 'Clark', 'susan.clark@example.com', 1, 5),
('Sarah', 'Rodriguez', 'sarah.rodriguez@example.com', 1, 6),
('Margaret', 'Lewis', 'margaret.lewis@example.com', 1, 7),
('Jessica', 'Lee', 'jessica.lee@example.com', 1, 1),
('Karen', 'Walker', 'karen.walker@example.com', 1, 2),
('Nancy', 'Hall', 'nancy.hall@example.com', 1, 3),
('Betty', 'Allen', 'betty.allen@example.com', 1, 4),
('Helen', 'Young', 'helen.young@example.com', 1, 5),
('Sandra', 'Hernandez', 'sandra.hernandez@example.com', 1, 6),
('Donna', 'King', 'donna.king@example.com', 1, 7),
('Carol', 'Wright', 'carol.wright@example.com', 1, 1),
('Ruth', 'Lopez', 'ruth.lopez@example.com', 1, 2),
('Sharon', 'Hill', 'sharon.hill@example.com', 1, 3),
('Michelle', 'Scott', 'michelle.scott@example.com', 1, 4),
('Laura', 'Green', 'laura.green@example.com', 1, 5),
('Kimberly', 'Adams', 'kimberly.adams@example.com', 1, 6),
('Deborah', 'Baker', 'deborah.baker@example.com', 1, 7),
('Emily', 'Gonzalez', 'emily.gonzalez@example.com', 1, 1),
('Amanda', 'Nelson', 'amanda.nelson@example.com', 1, 2),
('Melissa', 'Carter', 'melissa.carter@example.com', 1, 3),
('Stephanie', 'Mitchell', 'stephanie.mitchell@example.com', 1, 4),
('Rebecca', 'Perez', 'rebecca.perez@example.com', 1, 5),
('Laura', 'Roberts', 'laura.roberts@example.com', 1, 6),
('Sharon', 'Turner', 'sharon.turner@example.com', 1, 7),
('Cynthia', 'Phillips', 'cynthia.phillips@example.com', 1, 1),
('Kathleen', 'Campbell', 'kathleen.campbell@example.com', 1, 2),
('Shirley', 'Parker', 'shirley.parker@example.com', 1, 3),
('Amy', 'Evans', 'amy.evans@example.com', 1, 4),
('Angela', 'Edwards', 'angela.edwards@example.com', 1, 5),
('Helen', 'Collins', 'helen.collins@example.com', 1, 6),
('Anna', 'Stewart', 'anna.stewart@example.com', 1, 7),
('Brenda', 'Sanchez', 'brenda.sanchez@example.com', 1, 1),
('Pamela', 'Morris', 'pamela.morris@example.com', 1, 2),
('Nicole', 'Rogers', 'nicole.rogers@example.com', 1, 3),
('Lisa', 'Reed', 'lisa.reed@example.com', 1, 4),
('Catherine', 'Cook', 'catherine.cook@example.com', 1, 5),
('Virginia', 'Morgan', 'virginia.morgan@example.com', 1, 6),
('Kathryn', 'Bell', 'kathryn.bell@example.com', 1, 7),
('Debra', 'Murphy', 'debra.murphy@example.com', 1, 1),
('Rachel', 'Bailey', 'rachel.bailey@example.com', 1, 2),
('Janet', 'Rivera', 'janet.rivera@example.com', 1, 3),
('Carolyn', 'Cooper', 'carolyn.cooper@example.com', 1, 4),
('Christine', 'Richardson', 'christine.richardson@example.com', 1, 5),
('Marie', 'Cox', 'marie.cox@example.com', 1, 6),
('Julie', 'Howard', 'julie.howard@example.com', 1, 7),
('Heather', 'Ward', 'heather.ward@example.com', 1, 1),
('Diana', 'Torres', 'diana.torres@example.com', 1, 2),
('Kathy', 'Peterson', 'kathy.peterson@example.com', 1, 3),
('Theresa', 'Gray', 'theresa.gray@example.com', 1, 4),
('Beverly', 'Ramirez', 'beverly.ramirez@example.com', 1, 5),
('Denise', 'James', 'denise.james@example.com', 1, 6),
('Tammy', 'Watson', 'tammy.watson@example.com', 1, 7),
('Irene', 'Brooks', 'irene.brooks@example.com', 1, 1),
('Jane', 'Kelly', 'jane.kelly@example.com', 1, 2),
('Lori', 'Sanders', 'lori.sanders@example.com', 1, 3),
('Rachel', 'Price', 'rachel.price@example.com', 1, 4),
('Marilyn', 'Bennett', 'marilyn.bennett@example.com', 1, 5),
('Andrea', 'Wood', 'andrea.wood@example.com', 1, 6),
('Kathryn', 'Barnes', 'kathryn.barnes@example.com', 1, 7),
('Louise', 'Ross', 'louise.ross@example.com', 1, 1),
('Sara', 'Henderson', 'sara.henderson@example.com', 1, 2),
('Anne', 'Coleman', 'anne.coleman@example.com', 1, 3),
('Jacqueline', 'Jenkins', 'jacqueline.jenkins@example.com', 1, 4),
('Wanda', 'Perry', 'wanda.perry@example.com', 1, 5),
('Bonnie', 'Powell', 'bonnie.powell@example.com', 1, 6),
('Julia', 'Long', 'julia.long@example.com', 1, 7),
('Ruby', 'Patterson', 'ruby.patterson@example.com', 1, 1),
('Lois', 'Hughes', 'lois.hughes@example.com', 1, 2),
('Tina', 'Flores', 'tina.flores@example.com', 1, 3),
('Phyllis', 'Washington', 'phyllis.washington@example.com', 1, 4),
('Norma', 'Butler', 'norma.butler@example.com', 1, 5),
('Paula', 'Simmons', 'paula.simmons@example.com', 1, 6),
('Diana', 'Foster', 'diana.foster@example.com', 1, 7);
GO